INSERT INTO JOKES(`punchline`, `setup`, `type`)
VALUES ('An impasta.', 'What do you call a fake noodle?', 'general'),
       ('A metro-gnome', 'What do you call a fashionable lawn statue with an...', 'general'),
       ('A four-chin teller.', 'What do you call a fat psychic?', 'general'),
       ('A cat-tastrophe.', 'What do you call a group of disorganized cats?', 'general'),
       ('Shakespeare.', 'What do you call a nervous javelin thrower?', 'general'),
       ('A cloud.', 'What do you call a sheep with no legs?', 'general'),
       ('Park your car, man.', 'What do you do when you see a space man?', 'general'),
       ('A blood orange.', 'What is a vampire’s favorite fruit?', 'general'),
       ('punchline', 'setup', 'type'),
       ('The library, it’s got the most stories!', 'What is the tallest building in the world?', 'general'),
       ('A stega-snore-us.', 'What kind of dinosaur loves to sleep?', 'general'),
       ('MOODOO.', 'What kind of magic do cows believe in?', 'general'),
       ('Pop music!', 'What type of music do balloons hate?', 'general'),
       ('The second one.', 'What was a more important invention than the first...', 'general'),
       ('A stick.', 'What’s brown and sticky?', 'general'),
       ('They can"t control their pupils.', 'What’s the worst part about being a cross-eyed tea...', 'general'),
       ('Dung!', 'What’s brown and sounds like a bell?', 'general'),
       ('When it becomes apparent.', 'When does a joke become a dad joke?', 'general'),
       ('The BP station.', 'Where do bees go to the bathroom?', 'general'),
       ('At sundae school.', 'Where do you learn to make banana splits?', 'general'),
       ('Chick-Fil-Eyyyyyyyy.', 'Where does Fonzie like to go for lunch?', 'general'),
       ('At the bottom!', 'Where was the Declaration of Independence signed?', 'general'),
       ('I haven’t been anywhere!', 'Where’s the bin?', 'general'),
       ('The outside.', 'Which side of the chicken has more feathers?', 'general'),
       ('His ghoul-friend', 'Who did the wizard marry?', 'general'),
       ('The hip Doctor!', 'Who is the coolest Doctor in the hospital?', 'general'),
       ('Because you can see right through them!', 'Why are ghosts bad liars?', 'general'),
       ('They"re afraid to unwind.', 'Why are mummys scared of vacation?', 'general'),
       ('Because they are made to concentrate.', 'Why are oranges the smartest fruit?', 'general'),
       ('Because nothing gets under their skin.', 'Why are skeletons so calm?', 'general'),
       ('He was too far out, man.', 'Why couldn’t the lifeguard save the hippie?', 'general'),
       ('Because he had a vowel movement.', 'Why did the A go to the bathroom and come out as a...', 'general'),
       ('For fowl play.', 'Why did the chicken get a penalty?', 'general'),
       ('Because he was a little horse!', 'Why did the Clydesdale give the pony a glass of wa...', 'general'),
       ('It got mugged.', 'Why did the coffee file a police report?', 'general'),
       ('To go with the traffic jam.', 'Why did the girl smear peanut butter on the road?', 'general'),
       ('Because they cantaloupe!', 'Why did the melons plan a big wedding?', 'general'),
       ('It ran out of juice.', 'Why didn’t the orange win the race?', 'general'),
       ('So they can carry their tune', 'Why do choirs keep buckets handy?', 'general'),
       ('Because they"re so good at it.', 'Why do you never see elephants hiding in trees?', 'general'),
       ('Because it"s a little meteor.', 'Why does a Moon-rock taste better than an Earth-ro...', 'general'),
       ('Because there’s a Shortstop in between!', 'Why does it take longer to get from 1st to 2nd bas...', 'general'),
       ('A race condition. Who is there?', 'Knock-knock.', 'programming'),
       ('He goes nowhere.', 'An IPv6 packet is walking out of the house.', 'programming'),
       ('Dam.', 'What did the fish say when it hit the wall?', 'general'),
       ('A Dell', 'What do you call a singing Laptop', 'general'),
       ('You planet', 'How do you organize an outer space party?', 'general'),
       ('No, cows go moo.', 'Knock knock. Who’s there? Cows go. Cows go w...', 'knock-knock'),
       ('"Where is the bar tended?"', 'A termite walks into a bar and says...', 'general'),
       ('Because Oct 31 == Dec 25', 'Why do programmers always mix up Halloween and Chr...', 'programming'),
       ('None that"s a hardware problem', 'How many programmers does it take to change a ligh...', 'programming'),
       ('You must first understand what recursion is', 'To understand what recursion is...', 'programming'),
       ('Those who understand binary and those who don"t', 'There are 10 types of people in this world...',
        'programming'),
       ('Put it on my bill', 'What did the duck say when he bought lipstick?', 'general'),
       ('It gets toad away', 'What happens to a frog’s car when it breaks down?', 'general'),
       ('they were cooked in Greece', 'did you know the first French fries weren’t cooked...', 'general'),
       ('Because he was a fungi.', 'Why did the mushroom get invited to the party?', 'general'),
       ('Never mind...it"s tearable', 'Want to hear a joke about a piece of paper?', 'general'),
       ('Does that make you an iWitness?', 'If you see a robbery at an Apple Store...', 'general'),
       ('I woke up exhausted!', 'I had a dream that I was a muffler last night.', 'general'),
       ('Random Dude: [...💘]', 'Lady: How do I spread love in this cruel world?', 'general'),
       ('If you have to explain it then it is not that good...', 'A user interface is like a joke.', 'programming'),
       ('Despresso.', 'What do you call sad coffee?', 'general'),
       ('That’s a deep subject.', 'Well...', 'general'),
       ('They are always negative.', 'Never take advice from electrons.', 'general'),
       ('Join the club.', 'Bad at golf?', 'general'),
       ('There was nothing left but de Brie.', 'Did you hear about the cheese factory that explode...', 'general'),
       ('They say he made a mint.', 'Did you hear about the guy who invented Lifesavers...', 'general'),
       ('It"s ok, he woke up.', 'Did you hear about the kidnapping at school?', 'general'),
       ('He just took it in stride', 'Did you hear about the runner who was criticized?', 'general'),
       ('It really took a dive...', 'Did you hear about the submarine industry?', 'general'),
       ('It reads "Small medium at large."', 'Did you hear that the police have a warrant out on...', 'general'),
       ('The stock market.', 'Do you know where you can get chicken broth in bul...', 'general'),
       ('They haven"t got a gig yet.', 'Have you heard of the band 1023MB?', 'general'),
       ('A plain bagel.', 'What kind of bagel can fly?', 'general'),
       ('The sails are going through the roof.', 'I started a new business making yachts in my attic...', 'general'),
       ('Chess nuts boasting in an open foyer.', 'What do you call a crowd of chess players bragging...', 'general'),
       ('Because he is 2 square.', 'Why didn’t the number 4 get into the nightclub?', 'general'),
       ('Because they live in schools!', 'Why are fish so smart?', 'general'),
       ('They start coffin.', 'How can you tell a vampire has a cold?', 'general'),
       ('I woke up exhausted!', 'I had a dream that I was a muffler last night.', 'general'),
       ('It was udder destruction.', 'Did you hear about the cow who jumped over the bar...', 'general'),
       ('(hip hip array)', '[’hip’, ’hip’]', 'programming'),
       ('Because they"re so good at it.', 'Why do you never see elephants hiding in trees?', 'general'),
       ('In a nutshell, it"s an oak tree.', 'Do you want a brief explanation of what an acorn i...', 'general'),
       ('It gets jalapeño face.', 'What does an angry pepper do?', 'general'),
       ('A spelling bee.', 'What creature is smarter than a talking parrot?', 'general'),
       ('Ground beef!', 'What do you call a cow with no legs?', 'general'),
       ('There was nothing left but de Brie.', 'Did you hear about the cheese factory that explode...', 'general'),
       ('Hi, bud!', 'What did the big flower say to the littler flower?', 'general'),
       ('A stega-snore-us.', 'What kind of dinosaur loves to sleep?', 'general'),
       ('It goes back four seconds!', 'What does a clock do when it’s hungry?', 'general'),
       ('Don"t look I"m changing!', 'What did the traffic light say to the car as it pa...', 'general'),
       ('Put a little boogie in it.', 'How do you make a hankie dance?', 'general'),
       ('You boil the hell out of it.', 'How do you make holy water?', 'general'),
       ('You planet.', 'How do you organize a space party?', 'general'),
       ('You jacket.', 'How do you steal a coat?', 'general'),
       ('Make me one with everything.', 'What did the Zen Buddist say to the hotdog vendor?', 'general'),
       ('A wise quacker.', 'What do you call a duck that gets all A’s?', 'general'),
       ('Because it was rated arrr!', 'Why couldn’t the kid see the pirate movie?', 'general'),
       ('Hi, bud!', 'What did the big flower say to the littler flower?', 'general'),
       ('In a nutshell, it"s an oak tree.', 'Do you want a brief explanation of what an acorn i...', 'general'),
       ('Oh, it"s a really obscure number. You"ve probably ...',
        'How many hipsters does it take to change a lightbu...', 'general'),
       ('All of them!', 'How many apples grow on a tree?', 'general'),
       ('Tweets.', 'What do birds give out on Halloween?', 'general'),
       ('They are two tired', 'Why can’t bicycles stand on their own?', 'general'),
       ('A bah-humbug.', 'What do you get when you cross a bee and a sheep?', 'general'),
       ('Towels', 'What is the leading cause of dry skin?', 'general'),
       ('He"s all right now.', 'Did you hear about the guy whose whole left side w...', 'general'),
       ('Join the club.', 'Bad at golf?', 'general'),
       ('I want to hold your hand, hand, hand, hand...', 'What is a centipedes’s favorite Beatle song?', 'general'),
       ('At the bottom!', 'Where was the Declaration of Independence signed?', 'general'),
       ('Because they use a strongly typed language.', 'Why do C# and Java developers keep breaking their ...',
        'programming'),
       ('Nobody knows.', 'What do you call someone with no nose?', 'general'),
       ('They had a reptile dysfunction.', 'Did you hear about the chameleon who couldn’t chan...', 'general'),
       ('An instagram.', 'How much does a hipster weigh?', 'general'),
       ('Between us, something smells!', 'What did the left eye say to the right eye?', 'general'),
       ('Got stacks of em! First one"s on the house', 'Want to hear a chimney joke?', 'general'),
       ('Spelling!', 'What is a witch’s favorite subject in school?', 'general'),
       ('In a nutshell, it"s an oak tree.', 'Do you want a brief explanation of what an acorn i...', 'general'),
       ('He made a grave mistake.', 'Why did Dracula lie in the wrong coffin?', 'general'),
       ('I"m a cashew!', 'What did one nut say as he chased another nut?', 'general'),
       ('European', 'If you’re American when you go into the bathroom, ...', 'general'),
       ('Dinner is on me!', 'What did one plate say to the other plate?', 'general'),
       ('Lil Caesars', 'What did Romans use to cut pizza before the rollin...', 'general'),
       ('Nice belt.', 'What did the 0 say to the 8?', 'general'),
       ('Bark bark.', 'What did the dog say to the two trees?', 'general'),
       ('I’ll ketch up', 'What did the late tomato say to the early tomato?', 'general'),
       ('Between us, something smells!', 'What did the left eye say to the right eye?', 'general'),
       ('Cliff.', 'What did the mountain climber name his son?', 'general'),
       ('Nothing, it just waved.', 'What did the ocean say to the shore?', 'general'),
       ('Don"t look at me I"m changing!', 'What did the Red light say to the Green light?', 'general'),
       ('Don"t look I"m changing!', 'What did the traffic light say to the car as it pa...', 'general'),
       ('Make me one with everything.', 'What did the Zen Buddist say to the hotdog vendor?', 'general'),
       ('A milk shake!', 'What do you call a cow on a trampoline?', 'general'),
       ('Chess nuts boasting in an open foyer.', 'What do you call a crowd of chess players bragging...', 'general');

